import { Artwork } from "@/types/gallery";
import { ProvenanceNarrative } from "@/types/gallery";
import "./ProvenanceDossier.css";

interface ProvenanceDossierProps {
  artwork: Artwork;
  narrative?: ProvenanceNarrative | null;
}

export default function ProvenanceDossier({ artwork, narrative }: ProvenanceDossierProps) {
  return (
    <section className="provenance-dossier">
      <div className="dossier-header">
        <h2>Provenance Dossier</h2>
        <p className="dossier-subtitle">Complete Historical Record</p>
      </div>

      <div className="dossier-content">
        {/* Artwork Provenance */}
        {artwork.provenance && (
          <div className="provenance-section">
            <h3>Historical Provenance</h3>
            <p className="provenance-text">{artwork.provenance}</p>
          </div>
        )}

        {/* AI-Generated Narrative */}
        {narrative && (
          <div className="narrative-section">
            <h3>Expert Analysis</h3>
            <div className="narrative-content">
              <p>{narrative.narrative}</p>
              <p className="narrative-meta">
                Generated by: {narrative.generatedBy}
              </p>
            </div>
          </div>
        )}

        {/* Artwork Details */}
        <div className="details-section">
          <h3>Technical Details</h3>
          <div className="details-grid">
            {artwork.year && (
              <div className="detail-item">
                <span className="detail-label">Year Created:</span>
                <span className="detail-value">{artwork.year}</span>
              </div>
            )}
            {artwork.medium && (
              <div className="detail-item">
                <span className="detail-label">Medium:</span>
                <span className="detail-value">{artwork.medium}</span>
              </div>
            )}
            {artwork.dimensions && (
              <div className="detail-item">
                <span className="detail-label">Dimensions:</span>
                <span className="detail-value">{artwork.dimensions}</span>
              </div>
            )}
            {artwork.estimatedValue && (
              <div className="detail-item">
                <span className="detail-label">Estimated Value:</span>
                <span className="detail-value">{artwork.estimatedValue}</span>
              </div>
            )}
          </div>
        </div>

        {/* Description */}
        {artwork.description && (
          <div className="description-section">
            <h3>Description</h3>
            <p className="description-text">{artwork.description}</p>
          </div>
        )}
      </div>

      <div className="dossier-footer">
        <p className="certification">
          ✓ This provenance record has been verified and certified by NVAI.
        </p>
      </div>
    </section>
  );
}
